console.log(`maths object`);
let x = 34;
let y = 3;
let z;
z = x+y;
z = x-y;
z = x*y;
z = x/y;
z = Math;
z = Math.PI;
z = Math.E;
z = Math.ceil(5.4);
z = Math.round(5.7);
z = Math.floor(5.7);
z = Math.abs(-5.7);
z = Math.sqrt(49);
z = Math.pow(7,9);
z = Math.min(1,2,3,4,5,6,7,8,9);
z = Math.max(1,2,3,4,5,6,7,8,9);
z = Math.random();
z = Math.round(50+(100-50)*Math.random());//adding range
console.log(z);
